---

- name: Check if terraform binary version
  command: "{{ terraform_config_dir }}/bin/terraform -version"
  register: terraform_binary_check
  changed_when: false
  failed_when: false

- block:
#    - name: Install unzip
#      package:
#        name: unzip
#        state: present
#      become: true
#      when: ansible_os_family != "Darwin"

    - name: "Create directory for terraform binary {{ terraform_config_dir }}/bin"
      file:
        path: "{{ terraform_config_dir }}/bin"
        state: directory

    - name: Download and extract terraform binary
      unarchive:
        src: "https://releases.hashicorp.com/terraform/{{ terraform_binary_version }}/\
              terraform_{{ terraform_binary_version }}_{{ terraform_binary_platform }}.zip"
        dest: "{{ terraform_config_dir }}/bin"
        remote_src: yes
  when:
    - terraform_binary_check.rc != 0 or
      terraform_binary_check.stdout.splitlines()[0] != 'Terraform v' + terraform_binary_version
