---

- name: Purge Libvirt output directory
  file:
    path: "{{ terraform_config_dir }}"
    state: absent
  when:
    - terraform_purge | bool

- name: Create Libvirt output directory
  file:
    path: "{{ terraform_config_dir }}"
    state: directory

- name: Create Libvirt private output directory
  file:
    path: "{{ terraform_config_dir }}/private"
    state: directory
    mode: 0700

- name: Deploy Libvirt private variables source templates
  template:
    src: "libvirt/variables.source.j2"
    dest: "{{ terraform_config_dir }}/private/variables.source"
    mode: 0600

- name: Deploy Libvirt general resources templates
  template:
    src: "libvirt/{{ item }}.tf.j2"
    dest: "{{ terraform_config_dir }}/{{ item }}.tf"
  with_items:
    - 'provider'
    - 'networks'
    - 'pools'
    - 'volumes'
    - 'cloud_init'

# Deploy the cloud_init.cfg, for details look at:
# https://cloudinit.readthedocs.io/en/latest/reference/examples.html
- name: Deploy Libvirt cloud_init.cfg file
  copy:
    content: |
      #cloud-config
      {{ item.cfg | to_nice_yaml(indent=2, width=9999) }}
    dest: "{{ terraform_config_dir }}/cloud_init_{{ item.name }}.cfg"
  with_items:
    - "{{ terraform_libvirt_cloud_inits }}"

- name: Deploy Libvirt virtual machines specific templates
  include_tasks: libvirt-vms.yml
  with_items:
    - "{{ terraform_libvirt_vms_groups }}"
  loop_control:
    loop_var: terraform_group_name

- name: Display a reminder for sourcing variables
  debug:
    msg:
      - "Remember to import the variable file in order to tell Terraform which"
      - "subscription use during the run. Before run Terraform, please execute:"
      - "    source {{ terraform_config_dir }}/private/variables.source"
